#define _GNU_SOURCE 1
/* oodar runtime umbrella — single TU for existing gcc command lines.
 * Each #include pulls in a .c file from its owning subdir. The canonical
 * build command is `gcc oodar.c` from the repo root.
 *
 * Layout (mirrors std's vocabulary): sec/ fs/ net/ hw/ app/, with
 * core/ at the top for universal primitives. oodar.h and types.h
 * live at the root; subdir files include them as
 *   #include "../../oodar.h"
 *   #include "../../types.h"
 */
#include "sec/cap/caps.c"
#include "sec/landlock/landlock/landlock.c"
#include "sec/landlock/landlock/landlock_restrict.c"
#include "sec/landlock/sandbox/sandbox.c"
#include "sec/landlock/sandbox/sandbox_matrix.c"
#include "sec/landlock/sandbox/sandbox_config.c"
#include "sec/landlock/sandbox/sandbox_c.c"
#include "sec/landlock/proc_mem.c"
#include "sec/cap/cap.c"
#include "core/str/str.c"
#include "core/str/str_intern.c"
#include "core/str/str_from_int.c"
#include "core/str/str_tok.c"
#include "core/str/str_ops.c"
#include "app/telemetry/event.c"
#include "core/list/list.c"
#include "core/list/list_alloc.c"
#include "core/list/list_atomic.c"
#include "core/list/list_set.c"
#include "core/list/flist.c"
#include "core/list/llist.c"
#include "fs/os/sys_env.c"
#include "fs/os/sys_stamp.c"
#include "fs/os/sys_stdin.c"
#include "fs/os/sys.c"
#include "net/fetch.c"
#include "app/xlang/ffi_sec.c"
#include "app/xlang/ffi.c"
#include "sec/crypto/hash.c"
#include "fs/os/netfloor.c"
#include "fs/os/netfloor_tcp.c"
#include "fs/os/netfloor_udp.c"
#include "net/tls.c"
#include "hw/gpu/gpu/gpu.c"
#include "hw/gpu/gpu/gpu_atomic.c"
#include "hw/gpu/gpu/gpu_pool.c"
#include "hw/gpu/gpu/gpu_mem.c"
#include "hw/gpu/gpu/gpu_stream.c"
#include "hw/gpu/gpu/gpu_launch.c"
#include "hw/gpu/gpu/gpu_hip_dlopen.c"
#include "hw/gpu/gpu/gpu_hip_dispatch.c"
#include "hw/gpu/gpu/gpu_hip.c"
#include "app/actor/actor_thread.c"
#include "app/actor/actor_channel.c"
#include "app/actor/actor.c"
#include "app/actor/actor_rpc.c"
#include "app/hitl/hitl.c"
#include "fs/os/time_rand.c"
#include "core/mem/alloc.c"
#include "core/mem/arena.c"
#include "core/mem/arena_soa.c"
#include "core/mem/arena_dod.c"
#include "core/mem/arena_checkpoint.c"
#include "fs/os/fs_lowlevel.c"
#include "fs/os/fs_dir.c"
#include "fs/os/fs.c"
#include "app/io/print.c"
#include "core/math/math.c"
#include "sec/crypto/crypto.c"
#include "core/anti_emul/anti_emul.c"
#include "fs/os/host.c"
#include "fs/os/rlimit.c"
#include "fs/os/dns.c"
#include "app/xlang/xlang.c"
#include "sec/crypto/sha3.c"
#include "sec/crypto/aead.c"
#include "sec/crypto/seal.c"
#include "sec/pqc/mlkem.c"
#include "sec/pqc/mldsa.c"
#include "sec/pqc/pq_sig.c"
#include "app/telemetry/metrics.c"
#include "app/actor/actor_closure.c"
#include "core/mem/align.c"
#include "core/mem/weak.c"
