#define _GNU_SOURCE 1
/* oodar runtime umbrella — single TU for existing gcc command lines.
 * Each #include pulls in a .c file from its owning subdir. The canonical
 * build command is `gcc oodar.c` from the repo root.
 *
 * Layout (mirrors std's vocabulary): sec/ fs/ net/ hw/ app/, with
 * core/ at the top for universal primitives. oodar.h and types.h
 * live at the root; subdir files include them as
 *   #include "../../../oodar.h"
 *   #include "../../../types.h"
 */
#include "sec/cap/caps.c"
#include "sec/landlock/landlock.c"
#include "sec/landlock/sandbox.c"
#include "sec/cap/cap.c"
#include "core/str/str.c"
#include "core/str/str_intern.c"
#include "core/str/str_from_int.c"
#include "core/str/str_tok.c"
#include "core/str/str_ops.c"
#include "core/list/list.c"
#include "core/list/flist.c"
#include "core/list/llist.c"
#include "fs/os/sys.c"
#include "net/fetch.c"
#include "app/xlang/ffi_sec.c"
#include "app/xlang/ffi.c"
#include "sec/crypto/hash.c"
#include "fs/os/netfloor.c"
#include "net/tls.c"
#include "hw/gpu/gpu.c"
#include "hw/gpu/gpu_hip.c"
#include "app/actor/thread.c"
#include "app/actor/channel.c"
#include "app/actor/actor.c"
#include "app/hitl/hitl.c"
#include "fs/os/time_rand.c"
#include "core/mem/alloc.c"
#include "core/mem/arena.c"
#include "fs/os/fs.c"
#include "fs/io/print.c"
#include "core/math/math.c"
#include "sec/crypto/crypto.c"
#include "core/meta/meta.c"
#include "fs/os/host.c"
#include "fs/os/rlimit.c"
#include "fs/os/dns.c"
#include "app/xlang/xlang.c"
#include "sec/crypto/sha3.c"
#include "sec/crypto/aead.c"
#include "sec/pqc/mlkem.c"
#include "sec/pqc/mldsa.c"
#include "sec/pqc/pq_sig.c"
#include "app/telemetry/metrics.c"
#include "app/telemetry/event.c"
#include "app/actor/closure.c"
#include "core/mem/align.c"
