#define _GNU_SOURCE 1
#define OODAR_CRYPTO_INTERNAL 1
#include "oodar.h"
#include "oodar_internal.h"
#include "sec/crypto/sha3.c"
#include "sec/crypto/aead/aead.c"
#include "sec/crypto/aead/aes_gcm.c"
#include "sec/pqc/mlkem/mlkem_ntt.c"
#include "sec/pqc/mlkem/mlkem_sample.c"
#include "sec/pqc/mlkem/mlkem_poly.c"
#include "sec/pqc/mlkem/mlkem.c"
#include "sec/pqc/mlkem/mlkem_kem.c"
#include "sec/pqc/mldsa/mldsa_ntt.c"
#include "sec/pqc/mldsa/mldsa_poly.c"
#include "sec/pqc/mldsa/mldsa_sample.c"
#include "sec/pqc/mldsa/mldsa.c"
#include "sec/pqc/mldsa/mldsa_sign.c"
#include "sec/pqc/mldsa/mldsa_verify.c"
#include "sec/pqc/pq_sig/pq_sig.c"
#include "sec/pqc/pq_sig/pq_aead_seal.c"
#include "sec/pqc/pq_sig/pq_aead_open.c"
#include "sec/pqc/pq_sig/pq_hmac.c"
