#!/usr/bin/env python3
# scripts/gen_cap_table.py — Regenerate sec/cap/cap_table.json from sec/cap/caps.h
#
# Reads the OODAR_CAP_* #defines from caps.h and produces the JSON
# structural table that the lsp verifier and oodac consume. Run this
# whenever a cap is added, removed, renamed, or its bit position
# changes. The output is what `cap_table.json` SHOULD be; the script
# does not modify cap_table.json in place (the JSON has hand-curated
# "grantee" and "subsumes" fields that the script cannot infer).
#
# Usage:
#   python3 scripts/gen_cap_table.py > /tmp/expected.json
#   diff /tmp/expected.json sec/cap/cap_table.json
#
# Or to overwrite (after manually porting the hand-curated fields):
#   python3 scripts/gen_cap_table.py --check  # exit non-zero on mismatch

import re
import sys
import json

CAPS_H = "sec/cap/caps.h"
CAP_RE = re.compile(r"^#define\s+(OODAR_CAP_\w+)\s+(.+?)$")

# Hand-curated fields. Extend these when adding a cap.
NORTH_STAR = {
    "NET", "PROCESS", "FSWRITE", "FSREAD", "SYS", "FS",
    "TIME", "RAND", "ALLOC", "ARENA", "FFI", "METRICS", "SIGN",
}
IMPLEMENTED = NORTH_STAR | {"TCP", "UDP", "BIND", "THREAD", "GPU", "ENV"}
# Cap name -> oo_cap_require_xxx mapping. The caps use FSW/FSR in C but
# the function names use fs_w/fs_r (with the underscore for readability).
REQUIRE_FN = {
    "FSWRITE": "oo_cap_require_fs_write",
    "FSREAD":  "oo_cap_require_fs_read",
}
GRANTEES = {
    "NET":           "fs/os/netfloor.c, fs/os/netfloor_tcp.c, fs/os/netfloor_udp.c",
    "PROCESS":       "fs/os/sys.c (fork/execve)",
    "FSWRITE":       "fs/os/fs.c (open with O_WRONLY|O_CREAT|O_TRUNC)",
    "FSREAD":        "fs/os/fs.c (open with O_RDONLY)",
    "SYS":           "fs/os/sys.c (raw syscall shims)",
    "FS":            "fs/os/fs.c (path validation, dir iteration)",
    "TIME":          "fs/os/time_rand.c (monotonic clock)",
    "RAND":          "fs/os/time_rand.c (getentropy-derived rand)",
    "ALLOC":         "core/mem/alloc.c (oo_alloc/free)",
    "ARENA":         "core/mem/arena.c (oo_checkpoint/oo_rollback)",
    "FFI":           "app/xlang/ffi.c, app/xlang/ffi_sec.c",
    "METRICS":       "app/telemetry/metrics.c (oo_metrics_incr)",
    "SIGN":          "app/actor/actor_rpc.c (cap-RPC sign/verify)",
    "TCP":           "fs/os/netfloor_tcp.c",
    "UDP":           "fs/os/netfloor_udp.c (oo_udp_send/recv only)",
    "BIND":          "fs/os/netfloor_udp.c (oo_bind_udp), fs/os/netfloor_tcp.c (oo_bind_tcp)",
    "THREAD":        "app/actor/actor_thread.c (oo_thread_spawn)",
    "GPU":           "hw/gpu/gpu/gpu_hip.c (oo_gpu_hip_try_launch)",
    "ENV":           "fs/os/sys_env.c (policy getenv filter)",
}
SUBSUMES = {
    "FS":  ["FSREAD", "FSWRITE"],
    "NET": ["TCP", "UDP"],
}
# Unimplemented caps: grantee is a hint to where the implementer will
# live. Matches the canonical cap_table.json hand-curated format.
UNIMPLEMENTED_GRANTEES = {
    "AUDIO":         "(reserved for app/audio/)",
    "CAMERA":        "(reserved for app/camera/)",
    "USB":           "(reserved for hw/usb/)",
    "HID":           "(reserved for app/hid/)",
    "WINDOW":        "(reserved for app/window/)",
    "FRAME":         "(reserved for app/frame/)",
    "COMPILER_READ": "(reserved for oodac emit-time compile read)",
}

def parse_value(tok: str) -> int:
    tok = tok.strip()
    if tok.startswith("(") and tok.endswith(")"):
        tok = tok[1:-1].strip()
    if "<<" in tok:
        # form: "1u << N" or "1 << N"
        lhs, rhs = tok.split("<<", 1)
        if lhs.strip().rstrip("u").strip() == "1":
            return 1 << int(rhs.strip())
    if tok.endswith("u"):
        tok = tok[:-1]
    return int(tok, 0)

def main():
    caps = []
    with open(CAPS_H) as f:
        for line in f:
            m = CAP_RE.match(line)
            if not m:
                continue
            name_with_prefix, value = m.group(1), m.group(2)
            name = name_with_prefix[len("OODAR_CAP_"):]
            value_int = parse_value(value)
            if value_int == 0:
                continue  # placeholder
            bit = value_int.bit_length() - 1
            caps.append({
                "name": name,
                "value": value_int,
                "bit": bit,
                "implemented": name in IMPLEMENTED,
                "category": "north_star" if name in NORTH_STAR else "future_state",
                "grantee": GRANTEES.get(name, UNIMPLEMENTED_GRANTEES.get(name, f"(reserved — grantee TBD for {name.lower()})")),
                "require": REQUIRE_FN.get(name, f"oo_cap_require_{name.lower()}") if name in IMPLEMENTED else "(none — token reserved)",
                "subsumes": SUBSUMES.get(name, []),
            })

    caps.sort(key=lambda c: c["bit"])
    out = {
        "_comment": "Generated by scripts/gen_cap_table.py. Edit sec/cap/caps.h to add/remove caps; re-run this script and reconcile cap_table.json.",
        "_version": "3.1.1",
        "_generated_from": "sec/cap/caps.h",
        "cap_count": len(caps),
        "cap_count_implemented": sum(1 for c in caps if c["implemented"]),
        "cap_count_future_state": sum(1 for c in caps if not c["implemented"]),
        "audit_bit_position": 11,
        "audit_bit_value": 2048,
        "audit_bit_note": "v2.1.0 reserved bit 0x800 (the AUDIT bit) for future re-introduction. v3.0.0 re-introduced it as OODAR_CAP_METRICS.",
        "caps": caps,
        "subsumption_rules": [
            "FS subsumes FSREAD, FSWRITE",
            "NET subsumes TCP, UDP, BIND",
        ],
        "rule_2_attenuation_note": "v3.1.0 deferred. The bitmask subset check on oo_cap_attenuate (parent_rights & child_rights == child_rights) is the v3.2.0 Floor break. See CHANGES.md v3.1.0 § 'Deferred to v3.2.0 Floor break'.",
    }
    print(json.dumps(out, indent=2) + "\n")

if __name__ == "__main__":
    main()
