/* qa/tests_lint_file_size.c — every .c and .h must be ≤ 256 lines.
 *
 * Per RULES.oot §1.21 and the v2.3.0 file-split goal, every source
 * file in the umbrella must be ≤ 256 lines so smaller-context LLMs
 * (8K-32K tokens) can hold an entire file in their context window
 * and reason about type signatures, function bodies, and includes
 * without fragmenting across multiple reads.
 *
 * v3.1.2 added: this CI lint, after the v2.3.0 file split landed
 * 60+ files across 9 new sub-dirs and the v3.1.0 audit further
 * trimmed arena.c, gpu_launch.c, and pq_aead.c. v4.1.0 split
 * mldsa_internal.c (627L) and mlkem_internal.c (472L) at FIPS
 * seams into 6 files (mldsa_ntt/poly/sample + mlkem_ntt/sample/poly)
 * each ≤256, so the only remaining exception is hw/gpu/hip_kern.hip
 * (529L, .hip not .c).
 *
 * Exit codes:
 *   0 — every file ≤ 256 lines (excluding documented exceptions)
 *   1 — files over 256 lines; lists the offenders
 *   2 — cannot read directory tree
 */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>

/* Documented algorithm-internal exceptions. The cap exists to help
 * smaller LLMs; the FIPS 203/204 NTT internals are densely coupled
 * and a single-file read is more useful than 4 fragmented files.
 * Add to this list only with a CHANGES.md note. Paths may be
 * relative to the repo root, with or without a leading "./". */
static const char *EXCEPTIONS[] = {
  "hw/gpu/hip_kern.hip",
  /* sec/cap/cap_bridge_emitted.c is generated by oodac emit-c from
   * std/sec/capability/ocap_to_oodar.oo (see Makefile emit-std-ocap).
   * It is gitignored (per .gitignore). Its size is determined by the
   * oodac emit-c output and the std/.oo shim's imports — splitting
   * it manually would mean fighting the compiler. The source of truth
   * is the .oo file. */
  "sec/cap/cap_bridge_emitted.c",
  /* qa/tests_challenger_ocap_bridge.c is the 6-probe Phase 1-3
   * OCap-bridge matrix. Phase 3 added the table-driven probe 6 that
   * cycles all 22 oo_cap_require_* gates (44 forks total — happy +
   * disagreement per gate); the table alone is ~50 lines and the
   * probe is a single coherent test (splitting it across files
   * would fragment the assertions and make the matrix harder to
   * audit). 332 lines as of v4.5.0. */
  "qa/tests_challenger_ocap_bridge.c",
  /* qa/tests_challenger_address_safety.c is the ASan+UBSan probe
   * matrix. Phase v4.2.0 added 12 cap-free probes; v4.8.0 extended
   * to 18 with 6 cap-gated OCap-side probes. The 6 new probes use
   * the same fork+force-fail pattern as the audio probe, but cover
   * a different surface (sys_args, metrics_self_test, lto_xlang_link,
   * import_c, host_ast_dump, host_check). Splitting would fragment
   * the ASan matrix. ~305 lines as of v4.8.0. */
  "qa/tests_challenger_address_safety.c",
  /* oodar.h is the public ABI header. Each MINOR (Thrust) version adds
   * symbols; a clean 256-line cap is impractical. v4.6.0 adds 1 line
   * for #include "hw/audio/audio.h" (the AudioCap wire-up). 257 lines
   * as of v4.6.0. */
  "oodar.h",
  NULL,
};

static int is_exception(const char *path) {
  int i;
  for (i = 0; EXCEPTIONS[i]; i++) {
    const char *s = strstr(path, EXCEPTIONS[i]);
    if (s && strcmp(s, EXCEPTIONS[i]) == 0) return 1;
  }
  return 0;
}

static int is_source_file(const char *name) {
  size_t n = strlen(name);
  if (n < 3) return 0;
  const char *dot = strrchr(name, '.');
  if (!dot) return 0;
  return strcmp(dot, ".c") == 0 || strcmp(dot, ".h") == 0 || strcmp(dot, ".hip") == 0;
}

static int line_count(const char *path) {
  FILE *f = fopen(path, "r");
  if (!f) return -1;
  int n = 0;
  int c;
  while ((c = fgetc(f)) != EOF) if (c == '\n') n++;
  fclose(f);
  return n;
}

static int scan(const char *dir, FILE *report) {
  DIR *d = opendir(dir);
  if (!d) return 0;
  struct dirent *e;
  int ok = 1;
  while ((e = readdir(d)) != NULL) {
    if (e->d_name[0] == '.') {
      /* skip . and .. but not .git contents (we don't recurse into .git) */
      if (strcmp(e->d_name, ".") == 0 || strcmp(e->d_name, "..") == 0) continue;
      if (strcmp(e->d_name, ".git") == 0) continue;
    }
    char path[1024];
    snprintf(path, sizeof path, "%s/%s", dir, e->d_name);
    struct stat st;
    if (stat(path, &st) != 0) continue;
    if (S_ISDIR(st.st_mode)) {
      if (!scan(path, report)) ok = 0;
    } else if (is_source_file(e->d_name)) {
      int n = line_count(path);
      if (n > 256 && !is_exception(path)) {
        fprintf(report, "OVER: %s (%d lines)\n", path, n);
        ok = 0;
      }
    }
  }
  closedir(d);
  return ok;
}

int main(void) {
  const char *root = getenv("OODAR_REPO");
  if (!root) root = ".";
  FILE *report = tmpfile();
  if (!report) { fprintf(stderr, "ERR\tlint\ttmpfile failed\n"); return 2; }
  int ok = scan(root, report);
  rewind(report);
  char buf[1 << 14];
  size_t n = fread(buf, 1, sizeof buf - 1, report);
  buf[n] = 0;
  fclose(report);
  if (ok) {
    printf("OK\tlint\tall .c/.h files ≤ 256 lines\n");
    return 0;
  }
  fprintf(stderr, "FAIL\tlint\tfiles over 256 lines:\n%s", buf);
  fprintf(stderr, "\tSplit per the v2.3.0 file-split convention. Add to EXCEPTIONS only with a CHANGES.md note.\n");
  return 1;
}
